Fix NuGet Security Analysis warning (#3487)
* Fix npm run test error TS2345 for generator

* Revert "Fix npm run test error TS2345 for generator"

This reverts commit e49afb6c1f93f78b1d680827fa819e93434af606.

* Remove MyGet from nuget.config per ##[warning]NuGet Security Analysis

* Fix Django Component Governance security warning

* Fix Django 2.2 before 2.2.10 has a security vulnerability.

* Revert Django changes