Fix error TS2345 in typescript EchoBot and CoreBot, and in the Samples pipelines (#3407)
* Cast socket argument as any

* generate.test.ts cast argument services as any

* Switch to the fix in package.json files "@types/node": "^10.17.27",