Fix TS2345 in "npm run test" for generator (#3434)
* Fix npm run test error TS2345 for generator

* Revert "Fix npm run test error TS2345 for generator"

This reverts commit e49afb6c1f93f78b1d680827fa819e93434af606.

* Revert "Revert "Fix npm run test error TS2345 for generator""

This reverts commit 3ed9f12e63ad695067d18cbbc896c69aa1aa8825.

* Set versions in package.json files to "next"

* Set "@microsoft/bf-lu" version to "latest"