Eliminate sleep tasks in DotNet E2E Linux pipelines (#3585)
* Fix npm run test error TS2345 for generator

* Revert "Fix npm run test error TS2345 for generator"

This reverts commit e49afb6c1f93f78b1d680827fa819e93434af606.

* Fix Django Component Governance security warning

* Fix Django 2.2 before 2.2.10 has a security vulnerability.

* Remove task 'Sleep for 13 min 20 sec'

* Add back sleeps and retests for debugging

* Add more sleeps for debugging

* Remove all sleeps again

* Remove continueonerror

* Cleanup