Fix Component vulnerability CVE-2021-26701 (#3495)
* Fix npm run test error TS2345 for generator

* Revert "Fix npm run test error TS2345 for generator"

This reverts commit e49afb6c1f93f78b1d680827fa819e93434af606.

* Fix Django Component Governance security warning

* Fix Django 2.2 before 2.2.10 has a security vulnerability.

* Bump System.Text.Encodings.Web version from 4.5.0 to 4.5.1 in TeamsTaskModule.csproj

* Bump System.Text.Encodings.Web from 4.3.1 to 4.5.1