Upgrade restify dependency to 8.6.0 (#3601)
* Fix npm run test error TS2345 for generator

* Revert "Fix npm run test error TS2345 for generator"

This reverts commit e49afb6c1f93f78b1d680827fa819e93434af606.

* Fix Django Component Governance security warning

* Fix Django 2.2 before 2.2.10 has a security vulnerability.

* Update restify to v8.6.0

* Revert formatting in file.

* Fix formatting of packages.json

* Fix formatting 2

* Update restify