Make E2E Sample DotNet tests target the latest SDK v4 by default (#3622)
* Fix npm run test error TS2345 for generator

* Revert "Fix npm run test error TS2345 for generator"

This reverts commit e49afb6c1f93f78b1d680827fa819e93434af606.

* Fix Django Component Governance security warning

* Fix Django 2.2 before 2.2.10 has a security vulnerability.

* Fix linux builds to select latest v4

* Tweak display name

* Fix From Azure get version

* Fix From nuget get version

* From azure feed fix 2

* From Myget feed tweak

* Tweak win-test.yml